title: Vanilla OS Documentation
author: Vanilla OS Contributors
email: send@mirko.pm

assets: /assets
uploads: /uploads

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

url:"https://documentation.vanillaos.org"
plugins:
  - jekyll-sitemap
